# Generated by Django 2.0.4 on 2019-01-21 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_table_test_user'),
    ]

    operations = [
    ]
