# Generated by Django 2.0.4 on 2019-01-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190121_1138'),
    ]

    operations = [
    ]
