# Generated by Django 2.0.4 on 2019-02-18 00:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190121_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.CharField(default=datetime.datetime(2019, 2, 18, 0, 20, 24, 66704, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 0, 20, 29, 536704, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
